### ISSUE TITLE
not working on thunderstore

### ISSUE THREAD

**Issue by CrownScorpion** [PTac-h/KnockOutWarningMod#1]
i tested it in game without thunderstore and it works just fine but if i launch modded with thunderstore it does not work anymore is there anyway to launch the game through thunderstore modded and still have this mod work?

**Comment by PTac-h** [comment]
Did you use any other mod alongside K.O warning ?

**Comment by PTac-h** [comment]
Uploaded the new version (1.1.0) on Thunderstore, their launcher should see the update any minutes now.

**Comment by CrownScorpion** [comment]
yes i was using a few mods with it but only through thunderstore no other mods with it outside of thunderstore. When its updated on thunderstore it self i will let u know if it works with the mods i run thanks for the quick reply

**Comment by CrownScorpion** [comment]
it works but i was able to still be heard despite not being able to move or do anything after getting knocked out. But thanks for updating so quickly and making it work on the thunderstore

**Comment by CrownScorpion** [comment]
Still has that issue where being in the "knocked out" state (blurry vision) my mic can still be heard even tho in the config options mute on knockout is set to true. Also if im not wrong when your knocked out that is indicated by blurry vision if so it does not last long for me at all maybe 1-3 seconds but i cant move for 15-30 seconds but hear my footsteps. Could you add a config option to adjust the random max time you can be knocked out for.

**Comment by PTac-h** [comment]
Weird, can you provide the full list of mods you are using ? Maybe one of them is incompatible with mine ?

**Comment by CrownScorpion** [comment]
![image ](https://github.com/PTac-h/KnockOutWarningMod/assets/96143117/90ab3316-10a2-43c6-9c20-96cf420eb0f1)
![image (1)](https://github.com/PTac-h/KnockOutWarningMod/assets/96143117/ebfe2814-25e3-499a-b451-1f81168e6e1e)

**Comment by CrownScorpion** [comment]
i have not tested it with other people only while recording my self with the in game camera and it picks up my mic

**Comment by CrownScorpion** [comment]
i will test rq with no mods but yours to see if it acts the same way

**Comment by CrownScorpion** [comment]
with just knockoutwarning enabled it still hears me in game when im knocked out and the effect only last 1-3 seconds still.

**Comment by PTac-h** [comment]
I'm implementing Minimum and Maximum ragdoll time to be configurable through the .cfg file.
But i have no clue why your mic isn't turned off while you're knocked out.
I will investigate a bit more today.

**Comment by CrownScorpion** [comment]
alright thanks let me know when you update it and i will test and let you know how it is. Good luck bug hunting.

**Comment by PTac-h** [comment]
OK it's not as bad as i thought, but still kind of weird.
The camera is the issue.
To keep it short, my mod is looking for you voice object linked to your player, this gives it access to microphone controll etc...
I'm using this to control if the mic is in "isTransmiting" state or not.
This work fine for players, but the camera is still able to pickup your sound somehow.

**Comment by CrownScorpion** [comment]
ooo ok sorry about the confusion i have not had anyone to test it with in game so I just used the camera to test. What about the weird knocked out thing. The blurry vison only last for a few seconds but sometimes I lay on the ground for 10-15 seconds maybe longer and cant get up or do anything yet can hear my footsteps like im walking even tho im still laying on the ground unable to move.

**Comment by PTac-h** [comment]
I wasn't aware of the sound problem with camera, i was testing the feature with the debug function that plays back your mic audio in game but wasn't testing with the camera in hands. 
And for the foosteps sounds i think it's because i'm not disabling player controls, so the walking animation, wich isn't supposed to play in this state, triggers foosteps sound anyways.
Also i should point out in the README that the ragdoll duration is proportional to the force of the impact.
