### ISSUE TITLE
Blur too short when knocked out

### ISSUE THREAD

**Issue by PTac-h** [PTac-h/KnockOutWarningMod#4]
The blur effect should go away gradually depending of the ragdoll duration.

**Comment by CrownScorpion** [comment]
Quick suggestion about something like this if you dont mind. Would it be possible to have the face get turned off like what happens when you die but when you get knocked out as well and it comes back on when you get back up.

**Comment by PTac-h** [comment]
Implemented a new blur system, transition should now be way smoother

**Comment by CrownScorpion** [comment]
the sleep animation would be better instead of a blur effect but that is weird how it applies to the camera yet the blur effect does not

**Comment by PTac-h** [comment]
Found out that the sleep effect was applied to a renderer set to global (all cameras), move it's components to the player renderer to remove the effect of the camera's camera component
